# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd36433ea34147d51df9d1d997a89ed8cdab9e1ef375ea2ce41b9fb9c53a1b95ce811434cd5d744fe32086470c15334dc8fc3a10f743fcaea1ac88f0f4238ab

test:
  secret_key_base: 014967119983040271dd18aaa3a2819ff2e5c83dc032a32985f8fc5702049b383bcf87656168c13e5be5a38408af91288f68d11fa4b62c3fc14f61958dc9cfa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
