User.create!([
  {name: "Moreno Garcia e Silva", email: "gnumoreno@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "admin", activated: true, activated_at: Time.zone.now},
  {name: "Camila HochMüller Abadie", email: "cmhochmuller@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "admin", activated: true, activated_at: Time.zone.now},
  {name: "Lucas Guimarães", email: "lokaster@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "editor", activated: true, activated_at: Time.zone.now},
  {name: "Talles Tonatto", email: "talles.tonatto@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "admin", activated: true, activated_at: Time.zone.now},
  {name: "Gabriel Knüpfer", email: "gabriel.knupfer0910@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "admin", activated: true, activated_at: Time.zone.now},
  {name: "Gustavo Abadie", email: "gbabadie@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          role: "editor", activated: true, activated_at: Time.zone.now},
  {name: "Michael Hartl", email: "mhartl@example.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now},
  {name: "User Example", email: "example@railstutorial.org", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now},
  {name: "Evandro Ferreira", email: "ealost@live.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now},
  {name: "Luciano Schühli", email: "luciano.sch@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now},
  {name: "Francisco Escorsim", email: "foescorsim@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now},
  {name: "Luis Caldas", email: "caldasluis30@gmail.com", 
          password: "fooobaaar", password_confirmation: "fooobaaar", 
          activated: true, activated_at: Time.zone.now}
])