User.create!([
  {name: "Moreno Garcia e Silva", email: "gnumoreno@gmail.com", password_digest: "$2a$10$/geAYn34ViNxtoR9ygBcXOnfYiCANOWXxvmSx05SX3P58s9uFE7aC", remember_digest: nil, role: "admin", activation_digest: "$2a$10$kjJL0b7.RtzBGMLqtgjbIuv8aF6rv5Sasfz2L.RxhcMkfJYHmEeSm", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Camila HochMüller Abadie", email: "cmhochmuller@gmail.com", password_digest: "$2a$10$5W4x8Qr5DpVIc1uMpLanAOLERqOKwjcXzWMNXKh.Gd/cK/oxV5IwG", remember_digest: nil, role: "admin", activation_digest: "$2a$10$dU/R1fz9XyASa5DnEO1heueiPR6oiZOPC4sOBFiNCbvdpYI8rsP/W", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Lucas Guimarães", email: "lokaster@gmail.com", password_digest: "$2a$10$e2svR1u4oUMMREJT9JNZRO/EXxGAYkqhepPfwTr3eYNLJMQeNSeBC", remember_digest: nil, role: "editor", activation_digest: "$2a$10$1nj1HmhBvlwh1VUPqiOQEe8qiETc0uaNSHY/maDPTDNnHC0ftiFr2", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Talles Tonatto", email: "talles.tonatto@gmail.com", password_digest: "$2a$10$zq.89ifwxVGuhhJdHTBRU.sMAw8vpob/TTpsNb//DQ.38mU82x8ci", remember_digest: nil, role: "admin", activation_digest: "$2a$10$RFMSGAnSdgg91dam0TvlNeUGZmtShgf4AkF58dMYt6k6YAkquQx7G", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Gabriel Knüpfer", email: "gabriel.knupfer0910@gmail.com", password_digest: "$2a$10$zLzzzuXp4SKzH/qlN4lUOO6qrKBwZBrtqFtTOfUp..Ph.7m9tQZjq", remember_digest: nil, role: "admin", activation_digest: "$2a$10$uUR0IUUgKlhO3d1ptkFyleFhuKjDbHMdSWJRrsMpBt0KzI0Yjr/8i", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Gustavo Abadie", email: "gbabadie@gmail.com", password_digest: "$2a$10$eCA19TXD6OlS0RzgOX112efPpwdVNqkNkR/zi6yfkCZG2ZSNuFa4e", remember_digest: nil, role: "editor", activation_digest: "$2a$10$KOMsxzo5M0NKwrw.vp3fP.te2fKL3RV4vjeArPMFJNuVXu2ciQiOG", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Michael Hartl", email: "mhartl@example.com", password_digest: "$2a$10$2AqmJ.ys6NdapqRB7zJsEutgEgeCl3Bl2qBnpgQp8uFMzbaSfGe7O", remember_digest: nil, role: nil, activation_digest: "$2a$10$m5RfPFgC7VJMmlMauL2QE.6HKDYz4BSgob48on3.kKfTeusEzVFEi", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "User Example", email: "example@railstutorial.org", password_digest: "$2a$10$mWbe4HaZR0t2baDzY9gudOofBUvsKnRceQoq0EIFMZoup0sxTgGpa", remember_digest: nil, role: nil, activation_digest: "$2a$10$YP7uaEDJUxSyCahW40Paje.ny2OSRWRImknju5dDaNHArhYNuNJQi", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Evandro Ferreira", email: "ealost@live.com", password_digest: "$2a$10$Tm.xl62a.9SLG6nolD.5geQMxh8LF03ceDUR6PJI96X1xovbWUuB.", remember_digest: nil, role: nil, activation_digest: "$2a$10$B.jWSGnNTqBApDVRQLLKNeHUlGWM9UFOg9pCy2QWQqICBZjXC9LdO", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Luciano Schühli", email: "luciano.sch@gmail.com", password_digest: "$2a$10$Xzqv29WyjvY97spJYWUqBu6wMpKDJY7TI/q6Z0h2un7uM7s1C19..", remember_digest: nil, role: nil, activation_digest: "$2a$10$QNhIHUiDSJ9hhuFfiQQJmuyFSDf7xjoZpOY9nlSFIqKfR0S6CU6q2", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Francisco Escorsim", email: "foescorsim@gmail.com", password_digest: "$2a$10$7cBC/ifUTdm1PoDxycavAO9pdUwKtZ30jmEPrg44wSDy4LJKjR61i", remember_digest: nil, role: nil, activation_digest: "$2a$10$jw0ypKTlCYfigBiDtcPBXOCD/jDc3LXYRjjrWW5TeS3JOr37uBMbi", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil},
  {name: "Luis Caldas", email: "caldasluis30@gmail.com", password_digest: "$2a$10$9aed.fMq0ruhXpHlPF9.XOafJ9Su4KMAA8IWfm9lN4SF1q5Dd4Stm", remember_digest: nil, role: nil, activation_digest: "$2a$10$TLkSIJidzVK1aD/9kFwgOeCPIlAr4sJT5Sh5AiX56OivBdtDEcFUC", activated: true, activated_at: "2016-11-16 23:40:04", reset_digest: nil, reset_sent_at: nil}
])
p "Create #{User.count} users"